### PR TITLE
feat: add 5.16,support ubuntu22.04

### PR DESCRIPTION
**Pull request by haojunyu**
Add patch for kernel 5.16, support ubuntu22.04 lts

### CODE REVIEW

**Comment by mpeirone** [comment]
Tested on Ubuntu 22.10(5.19.0-23-generic) it works.
Thanks a lot @haojunyu

**Comment by pkwagner** [comment]
Worked for me, thanks!

**Comment by wareck** [comment]
working for me , thanks !
but I needed to rollback to 5.15 for other reason (nvme driver fail)
I used this patch to build a patch for 5.15 "hunderd" kernel (works for me on 5.15.105 to 5.15.107
Thanks

**Comment by forrestsocool** [comment]
Tested on Ubuntu 22.04(5.19.0-32-generic), it works! Thank you very much!

**Pull request merged**
